name: Update Dependencies

on:
  workflow_dispatch:
  # schedule:
  # - cron: 30 10 * * *

env:
  # Use docker.io for Docker Hub if empty
  NXLOG_FILE_DOWNLOAD: https://dl.nxlog.co/dl/multiple/63bd48c2c637e?file_id=nxlog-ce/3.1.2319/nxlog-ce-3.1.2319.msi
  NXLOG_SAVE_LOCATION: nxlog.msi
  NXLOG_SAVE_LOCATION_TEMP: nxlog-tmp.msi
  SYSMON_FILE_DOWNLOAD: https://download.sysinternals.com/files/Sysmon.zip
  SYSMON_SAVE_LOCATION: sysmon.zip
  SYSMON_SAVE_LOCATION_TEMP: sysmon-tmp.zip

jobs:
  update:
    if: github.repository == 'robemmerson/mdr-supporting-files'
    name: Update
    runs-on: 'ubuntu-latest' # 'windows-latest' # [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Determine NxLog Version
        id: nxlog-version
        run: |
          version=$(curl -s https://gitlab.com/nxlog-public/nxlog-ce/-/raw/master/ChangeLog.txt | head -n1 | cut -d' ' -f3)
          nxlogfile=https://nxlog.co/system/files/products/files/348/nxlog-ce-$version.msi
          filecheck=$(curl -o /dev/null --silent -Iw '%{http_code}' $nxlogfile)
          if [[ $filecheck = '200' ]]; then \
            echo "NxLog file found, proceeding to check for update..."; \
            echo NXLOG_FILE_DOWNLOAD=$nxlogfile >>$GITHUB_ENV; \
          else \
            echo "NxLog file NOT found, reporting error..." && \
            echo NXLOG_ERROR="File cannot be found: $nxlogfile" >>$GITHUB_ENV; \
          fi

      - name: Check for NxLog Update
        id: nxlog
        run: |
          wget ${{ env.NXLOG_FILE_DOWNLOAD }} -O ${{ env.NXLOG_SAVE_LOCATION_TEMP }}
          NxLogExisting=$(md5sum ${{ env.NXLOG_SAVE_LOCATION }} | cut -f1 -d' ')
          NxLogNew=$(md5sum ${{ env.NXLOG_SAVE_LOCATION_TEMP }} | cut -f1 -d' ')
          echo "NxLogExisting is set to: $NxLogExisting"
          echo "NxLogNew is set to: $NxLogNew"
          if [[ ! $NxLogExisting = $NxLogNew ]]; then \
            echo "Updating NxLog" && \
            mv ${{ env.NXLOG_SAVE_LOCATION_TEMP }} ${{ env.NXLOG_SAVE_LOCATION }} && \
            echo GitBranchHash=$(date +%s) >>$GITHUB_ENV; \
          else \
            echo "No update, removing temporary file" && \
            rm -f ${{ env.NXLOG_SAVE_LOCATION_TEMP }}; \
          fi

      - name: Check for Sysmon Update
        run: |
          wget ${{ env.SYSMON_FILE_DOWNLOAD }} -O ${{ env.SYSMON_SAVE_LOCATION_TEMP }}
          SysmonExisting=$(md5sum ${{ env.SYSMON_SAVE_LOCATION }} | cut -f1 -d' ')
          SysmonNew=$(md5sum ${{ env.SYSMON_SAVE_LOCATION_TEMP }} | cut -f1 -d' ')
          echo "SysmonExisting is set to: $SysmonExisting"
          echo "SysmonNew is set to: $SysmonNew"
          if [[ ! $SysmonExisting = $SysmonNew ]]; then \
            echo "Updating Sysmon" && \
            mv ${{ env.SYSMON_SAVE_LOCATION_TEMP }} ${{ env.SYSMON_SAVE_LOCATION }} && \
            echo GitBranchHash=$(date +%s) >>$GITHUB_ENV; \
          else \
            echo "No update, removing temporary file" && \
            rm -f ${{ env.SYSMON_SAVE_LOCATION_TEMP }}; \
          fi

      - name: Setup Git
        if: env.GitBranchHash != ''
        run: |
          git config --global user.email "rob.emmerson@gmail.com"
          git config --global user.name "Rob Emmerson"
      
      - name: Commit and Push
        if: env.GitBranchHash != ''
        run: |
          echo "GitBranchHash is set to: $GitBranchHash"
          if [ ! -z ${GitBranchHash+x} ]; then \
            git checkout -b update-$GitBranchHash && \
            git add -A && \
            git commit -m 'Automatic Update' && \
            git push -u origin update-$GitBranchHash; \
          else \
            echo "No update required"; \
          fi
          
      - name: Create Pull Request
        if: env.GitBranchHash != ''
        run: |
          echo PullReq=$(curl \
          -s -f -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/robemmerson/mdr-supporting-files/pulls \
          -d '{"base":"main","head":"update-${{ env.GitBranchHash }}","title":"Merge update into main","body":"Created automatically with a Github action."}' \
          | jq .html_url) >>$GITHUB_ENV;

      - name: Notify Rob via Telegram
        uses: appleboy/telegram-action@2e9996f96e095a537aa4442da4af41ca7b594fba
        if: env.PullReq != ''
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            MDR Supporting Files requires an update!
            
            A pull request has been opened automatically, click here to view it: ${{ env.PullReq }}

      - name: Notify Rob via Telegram about errors
        uses: appleboy/telegram-action@2e9996f96e095a537aa4442da4af41ca7b594fba
        if: env.NXLOG_ERROR != ''
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            MDR Supporting Files has an issue with NxLog!
            
            The URL ${{ env.NXLOG_ERROR }} doesn't exist
